/* eslint-disable */
/**
 * This file was generated by 'vite-plugin-kit-routes'
 *
 *      >> DO NOT EDIT THIS FILE MANUALLY <<
 */

/**
 * PAGES
 */
const PAGES = {
  "/auth/alterar-senha": `/auth/alterar-senha`,
  "/auth/cadastro": `/auth/cadastro`,
  "/auth/confirmar-email": `/auth/confirmar-email`,
  "/auth/login": (params?: { redirect?: (string) }) => {
    return `/auth/login${appendSp({ 'redirect': params?.['redirect'] })}`
  },
  "/auth/logout": `/auth/logout`,
  "/auth/recuperar-senha": `/auth/recuperar-senha`,
  "/client": `/client`,
  "/client/configuracoes/organizacao": `/client/configuracoes/organizacao`,
  "/client/configuracoes/perfil": `/client/configuracoes/perfil`,
  "/client/configuracoes/seguranca": (params?: { redirectHereDueToForcePasswordChange?: (string) }) => {
    return `/client/configuracoes/seguranca${appendSp({ 'redirectHereDueToForcePasswordChange': params?.['redirectHereDueToForcePasswordChange'] })}`
  },
  "/client/configuracoes/sessoes": `/client/configuracoes/sessoes`,
  "/client/meu-perfil": `/client/meu-perfil`,
  "/client/niveis-acesso": `/client/niveis-acesso`,
  "/client/niveis-acesso/[access_level_id=integer]": (params: { access_level_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/niveis-acesso/${params['access_level_id']}`
  },
  "/client/niveis-acesso/novo": `/client/niveis-acesso/novo`,
  "/client/rastreamento/cartoes-sim": `/client/rastreamento/cartoes-sim`,
  "/client/rastreamento/cartoes-sim/[sim_card_id=integer]": (params: { sim_card_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/cartoes-sim/${params['sim_card_id']}`
  },
  "/client/rastreamento/cartoes-sim/novo": `/client/rastreamento/cartoes-sim/novo`,
  "/client/rastreamento/frotas": `/client/rastreamento/frotas`,
  "/client/rastreamento/frotas/[fleet_id=integer]": (params: { fleet_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/frotas/${params['fleet_id']}`
  },
  "/client/rastreamento/frotas/novo": `/client/rastreamento/frotas/novo`,
  "/client/rastreamento/mapa": (params?: { lookupTracker?: (number) }) => {
    return `/client/rastreamento/mapa${appendSp({ 'lookupTracker': params?.['lookupTracker'] })}`
  },
  "/client/rastreamento/rastreadores": `/client/rastreamento/rastreadores`,
  "/client/rastreamento/rastreadores/[tracker_id=integer]": (params: { tracker_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/rastreadores/${params['tracker_id']}`
  },
  "/client/rastreamento/rastreadores/novo": `/client/rastreamento/rastreadores/novo`,
  "/client/rastreamento/veiculos": `/client/rastreamento/veiculos`,
  "/client/rastreamento/veiculos/[vehicle_id=integer]": (params: { vehicle_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/veiculos/${params['vehicle_id']}`
  },
  "/client/rastreamento/veiculos/novo": `/client/rastreamento/veiculos/novo`,
  "/client/usuarios": `/client/usuarios`,
  "/client/usuarios/[user_id=integer]": (params: { user_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/usuarios/${params['user_id']}`
  },
  "/client/usuarios/novo": `/client/usuarios/novo`
}

/**
 * SERVERS
 */
const SERVERS = {
  "POST /auth/confirmar-email": `/auth/confirmar-email`,
  "POST /auth/logout": `/auth/logout`,
  "DELETE /auth/logout/[session_id=integer]": (params: { session_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/auth/logout/${params['session_id']}`
  },
  "POST /auth/requisitar-email-de-confirmacao": `/auth/requisitar-email-de-confirmacao`,
  "PUT /client/configuracoes/perfil/foto": `/client/configuracoes/perfil/foto`,
  "DELETE /client/configuracoes/perfil/foto": `/client/configuracoes/perfil/foto`,
  "GET /client/niveis-acesso": `/client/niveis-acesso`,
  "DELETE /client/niveis-acesso/[access_level_id=integer]": (params: { access_level_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/niveis-acesso/${params['access_level_id']}`
  },
  "GET /client/rastreamento/cartoes-sim": `/client/rastreamento/cartoes-sim`,
  "DELETE /client/rastreamento/cartoes-sim/[sim_card_id=integer]": (params: { sim_card_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/cartoes-sim/${params['sim_card_id']}`
  },
  "PUT /client/rastreamento/cartoes-sim/[sim_card_id=integer]": (params: { sim_card_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/cartoes-sim/${params['sim_card_id']}`
  },
  "GET /client/rastreamento/frotas": `/client/rastreamento/frotas`,
  "DELETE /client/rastreamento/frotas/[fleet_id=integer]": (params: { fleet_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/frotas/${params['fleet_id']}`
  },
  "PUT /client/rastreamento/frotas/[fleet_id=integer]": (params: { fleet_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/frotas/${params['fleet_id']}`
  },
  "GET /client/rastreamento/rastreadores": `/client/rastreamento/rastreadores`,
  "DELETE /client/rastreamento/rastreadores/[tracker_id=integer]": (params: { tracker_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/rastreadores/${params['tracker_id']}`
  },
  "PUT /client/rastreamento/rastreadores/[tracker_id=integer]": (params: { tracker_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/rastreadores/${params['tracker_id']}`
  },
  "GET /client/rastreamento/rastreadores/[tracker_id=integer]/localizacoes": (params: { tracker_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/rastreadores/${params['tracker_id']}/localizacoes`
  },
  "GET /client/rastreamento/rastreadores/[tracker_id=integer]/ultima-localizacao": (params: { tracker_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/rastreadores/${params['tracker_id']}/ultima-localizacao`
  },
  "POST /client/rastreamento/rastreadores/posicoes": `/client/rastreamento/rastreadores/posicoes`,
  "GET /client/rastreamento/veiculos": `/client/rastreamento/veiculos`,
  "DELETE /client/rastreamento/veiculos/[vehicle_id=integer]": (params: { vehicle_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/veiculos/${params['vehicle_id']}`
  },
  "GET /client/rastreamento/veiculos/[vehicle_id=integer]": (params: { vehicle_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/veiculos/${params['vehicle_id']}`
  },
  "PUT /client/rastreamento/veiculos/[vehicle_id=integer]/foto": (params: { vehicle_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/veiculos/${params['vehicle_id']}/foto`
  },
  "DELETE /client/rastreamento/veiculos/[vehicle_id=integer]/foto": (params: { vehicle_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/veiculos/${params['vehicle_id']}/foto`
  },
  "GET /client/usuarios": `/client/usuarios`,
  "DELETE /client/usuarios/[user_id=integer]": (params: { user_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/usuarios/${params['user_id']}`
  },
  "POST /client/usuarios/[user_id=integer]/bloquear": (params: { user_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/usuarios/${params['user_id']}/bloquear`
  },
  "POST /client/usuarios/[user_id=integer]/desbloquear": (params: { user_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/usuarios/${params['user_id']}/desbloquear`
  },
  "PUT /client/usuarios/[user_id=integer]/nivel-acesso": (params: { user_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/usuarios/${params['user_id']}/nivel-acesso`
  },
  "DELETE /client/usuarios/[user_id=integer]/sessoes/[session_id=integer]": (params: { user_id: (ExtractParamType<typeof import('../params/integer.ts').match>), session_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/usuarios/${params['user_id']}/sessoes/${params['session_id']}`
  },
  "GET /healthcheck": `/healthcheck`
}

/**
 * ACTIONS
 */
const ACTIONS = {
  "changePassword /auth/alterar-senha": `/auth/alterar-senha?/changePassword`,
  "signUp /auth/cadastro": `/auth/cadastro?/signUp`,
  "signIn /auth/login": `/auth/login?/signIn`,
  "recoverPassword /auth/recuperar-senha": `/auth/recuperar-senha?/recoverPassword`,
  "updateOrganization /client/configuracoes/organizacao": `/client/configuracoes/organizacao?/updateOrganization`,
  "updateProfile /client/configuracoes/perfil": `/client/configuracoes/perfil?/updateProfile`,
  "updateProfilePicture /client/configuracoes/perfil": `/client/configuracoes/perfil?/updateProfilePicture`,
  "changePassword /client/configuracoes/seguranca": `/client/configuracoes/seguranca?/changePassword`,
  "updateAccessLevel /client/niveis-acesso/[access_level_id=integer]": (params: { access_level_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/niveis-acesso/${params['access_level_id']}?/updateAccessLevel`
  },
  "createAccessLevel /client/niveis-acesso/novo": `/client/niveis-acesso/novo?/createAccessLevel`,
  "updateSimCard /client/rastreamento/cartoes-sim/[sim_card_id=integer]": (params: { sim_card_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/cartoes-sim/${params['sim_card_id']}?/updateSimCard`
  },
  "createSimCard /client/rastreamento/cartoes-sim/novo": `/client/rastreamento/cartoes-sim/novo?/createSimCard`,
  "updateFleet /client/rastreamento/frotas/[fleet_id=integer]": (params: { fleet_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/frotas/${params['fleet_id']}?/updateFleet`
  },
  "createFleet /client/rastreamento/frotas/novo": `/client/rastreamento/frotas/novo?/createFleet`,
  "updateTracker /client/rastreamento/rastreadores/[tracker_id=integer]": (params: { tracker_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/rastreadores/${params['tracker_id']}?/updateTracker`
  },
  "createTracker /client/rastreamento/rastreadores/novo": `/client/rastreamento/rastreadores/novo?/createTracker`,
  "updateVehicle /client/rastreamento/veiculos/[vehicle_id=integer]": (params: { vehicle_id: (ExtractParamType<typeof import('../params/integer.ts').match>) }) => {
    return `/client/rastreamento/veiculos/${params['vehicle_id']}?/updateVehicle`
  },
  "createVehicle /client/rastreamento/veiculos/novo": `/client/rastreamento/veiculos/novo?/createVehicle`,
  "createUser /client/usuarios/novo": `/client/usuarios/novo?/createUser`
}

/**
 * LINKS
 */
const LINKS = {
  
}

type ParamValue = string | number | undefined

/**
 * Append search params to a string
 */
export const appendSp = (
  sp?: Record<string, ParamValue | ParamValue[]>,
  prefix: '?' | '&' = '?',
) => {
  if (sp === undefined) return ''

  const params = new URLSearchParams()
  const append = (n: string, v: ParamValue) => {
    if (v !== undefined) {
      params.append(n, String(v))
    }
  }

  let anchor = ''
  for (const [name, val] of Object.entries(sp)) {
    if (name === '__KIT_ROUTES_ANCHOR__' && val !== undefined) {
      anchor = `#${val}`
      continue
    }
    if (Array.isArray(val)) {
      for (const v of val) {
        append(name, v)
      }
    } else {
      append(name, val)
    }
  }

  const formatted = params.toString()
  if (formatted || anchor) {
    return `${prefix}${formatted}${anchor}`.replace('?#', '#')
  }
  return ''
}

/**
 * get the current search params
 * 
 * Could be use like this:
 * ```
 * route("/cities", { page: 2 }, { ...currentSP() })
 * ```
 */ 
export const currentSp = () => {
  const params = new URLSearchParams(window.location.search)
  const record: Record<string, string> = {}
  for (const [key, value] of params.entries()) {
    record[key] = value
  }
  return record
}

/* type helpers for route function */
type NonFunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? never : K }[keyof T]
type FunctionKeys<T> = { [K in keyof T]: T[K] extends Function ? K : never }[keyof T]
type FunctionParams<T> = T extends (...args: infer P) => any ? P : never

const AllObjs = { ...PAGES, ...ACTIONS, ...SERVERS, ...LINKS }
type AllTypes = typeof AllObjs

export type Routes = keyof AllTypes extends `${string}/${infer Route}` ? `/${Route}` : keyof AllTypes
export const routes = [
	...new Set(Object.keys(AllObjs).map((route) => /^\/.*|[^ ]?\/.*$/.exec(route)?.[0] ?? route)),
] as Routes[]

/**
 * To be used like this: 
 * ```ts
 * import { route } from './ROUTES'
 * 
 * route('site_id', { id: 1 })
 * ```
 */
export function route<T extends FunctionKeys<AllTypes>>(key: T, ...params: FunctionParams<AllTypes[T]>): string
export function route<T extends NonFunctionKeys<AllTypes>>(key: T): string
export function route<T extends keyof AllTypes>(key: T, ...params: any[]): string {
  if (AllObjs[key] as any instanceof Function) {
    const element = (AllObjs as any)[key] as (...args: any[]) => string
    return element(...params)
  } else {
    return AllObjs[key] as string
  }
}

/* type helpers param & predicate */
type ExtractFnPredicate<T> = T extends (param: any) => param is infer U ? U : never;
type ExtractParamType<T extends (param: any) => any> = ExtractFnPredicate<T> extends never ? Parameters<T>[0] : ExtractFnPredicate<T>

/**
* Add this type as a generic of the vite plugin `kitRoutes<KIT_ROUTES>`.
*
* Full example:
* ```ts
* import type { KIT_ROUTES } from '$lib/ROUTES'
* import { kitRoutes } from 'vite-plugin-kit-routes'
*
* kitRoutes<KIT_ROUTES>({
*  PAGES: {
*    // here, key of object will be typed!
*  }
* })
* ```
*/
export type KIT_ROUTES = {
  PAGES: { '/auth/alterar-senha': never, '/auth/cadastro': never, '/auth/confirmar-email': never, '/auth/login': never, '/auth/logout': never, '/auth/recuperar-senha': never, '/client': never, '/client/configuracoes/organizacao': never, '/client/configuracoes/perfil': never, '/client/configuracoes/seguranca': never, '/client/configuracoes/sessoes': never, '/client/meu-perfil': never, '/client/niveis-acesso': never, '/client/niveis-acesso/[access_level_id=integer]': 'access_level_id', '/client/niveis-acesso/novo': never, '/client/rastreamento/cartoes-sim': never, '/client/rastreamento/cartoes-sim/[sim_card_id=integer]': 'sim_card_id', '/client/rastreamento/cartoes-sim/novo': never, '/client/rastreamento/frotas': never, '/client/rastreamento/frotas/[fleet_id=integer]': 'fleet_id', '/client/rastreamento/frotas/novo': never, '/client/rastreamento/mapa': never, '/client/rastreamento/rastreadores': never, '/client/rastreamento/rastreadores/[tracker_id=integer]': 'tracker_id', '/client/rastreamento/rastreadores/novo': never, '/client/rastreamento/veiculos': never, '/client/rastreamento/veiculos/[vehicle_id=integer]': 'vehicle_id', '/client/rastreamento/veiculos/novo': never, '/client/usuarios': never, '/client/usuarios/[user_id=integer]': 'user_id', '/client/usuarios/novo': never }
  SERVERS: { 'POST /auth/confirmar-email': never, 'POST /auth/logout': never, 'DELETE /auth/logout/[session_id=integer]': 'session_id', 'POST /auth/requisitar-email-de-confirmacao': never, 'PUT /client/configuracoes/perfil/foto': never, 'DELETE /client/configuracoes/perfil/foto': never, 'GET /client/niveis-acesso': never, 'DELETE /client/niveis-acesso/[access_level_id=integer]': 'access_level_id', 'GET /client/rastreamento/cartoes-sim': never, 'DELETE /client/rastreamento/cartoes-sim/[sim_card_id=integer]': 'sim_card_id', 'PUT /client/rastreamento/cartoes-sim/[sim_card_id=integer]': 'sim_card_id', 'GET /client/rastreamento/frotas': never, 'DELETE /client/rastreamento/frotas/[fleet_id=integer]': 'fleet_id', 'PUT /client/rastreamento/frotas/[fleet_id=integer]': 'fleet_id', 'GET /client/rastreamento/rastreadores': never, 'DELETE /client/rastreamento/rastreadores/[tracker_id=integer]': 'tracker_id', 'PUT /client/rastreamento/rastreadores/[tracker_id=integer]': 'tracker_id', 'GET /client/rastreamento/rastreadores/[tracker_id=integer]/localizacoes': 'tracker_id', 'GET /client/rastreamento/rastreadores/[tracker_id=integer]/ultima-localizacao': 'tracker_id', 'POST /client/rastreamento/rastreadores/posicoes': never, 'GET /client/rastreamento/veiculos': never, 'DELETE /client/rastreamento/veiculos/[vehicle_id=integer]': 'vehicle_id', 'GET /client/rastreamento/veiculos/[vehicle_id=integer]': 'vehicle_id', 'PUT /client/rastreamento/veiculos/[vehicle_id=integer]/foto': 'vehicle_id', 'DELETE /client/rastreamento/veiculos/[vehicle_id=integer]/foto': 'vehicle_id', 'GET /client/usuarios': never, 'DELETE /client/usuarios/[user_id=integer]': 'user_id', 'POST /client/usuarios/[user_id=integer]/bloquear': 'user_id', 'POST /client/usuarios/[user_id=integer]/desbloquear': 'user_id', 'PUT /client/usuarios/[user_id=integer]/nivel-acesso': 'user_id', 'DELETE /client/usuarios/[user_id=integer]/sessoes/[session_id=integer]': 'user_id' | 'session_id', 'GET /healthcheck': never }
  ACTIONS: { 'changePassword /auth/alterar-senha': never, 'signUp /auth/cadastro': never, 'signIn /auth/login': never, 'recoverPassword /auth/recuperar-senha': never, 'updateOrganization /client/configuracoes/organizacao': never, 'updateProfile /client/configuracoes/perfil': never, 'updateProfilePicture /client/configuracoes/perfil': never, 'changePassword /client/configuracoes/seguranca': never, 'updateAccessLevel /client/niveis-acesso/[access_level_id=integer]': 'access_level_id', 'createAccessLevel /client/niveis-acesso/novo': never, 'updateSimCard /client/rastreamento/cartoes-sim/[sim_card_id=integer]': 'sim_card_id', 'createSimCard /client/rastreamento/cartoes-sim/novo': never, 'updateFleet /client/rastreamento/frotas/[fleet_id=integer]': 'fleet_id', 'createFleet /client/rastreamento/frotas/novo': never, 'updateTracker /client/rastreamento/rastreadores/[tracker_id=integer]': 'tracker_id', 'createTracker /client/rastreamento/rastreadores/novo': never, 'updateVehicle /client/rastreamento/veiculos/[vehicle_id=integer]': 'vehicle_id', 'createVehicle /client/rastreamento/veiculos/novo': never, 'createUser /client/usuarios/novo': never }
  LINKS: Record<string, never>
  Params: { 'redirect': never, 'redirectHereDueToForcePasswordChange': never, 'access_level_id': never, 'sim_card_id': never, 'fleet_id': never, 'lookupTracker': never, 'tracker_id': never, 'vehicle_id': never, 'user_id': never, 'session_id': never }
}
