export const colors = [
	'Absolute Zero',
	'Acid Green',
	'Aero',
	'Aero Blue',
	'African Violet',
	'Air Force Blue (RAF)',
	'Air Force Blue (USAF)',
	'Air Superiority Blue',
	'Alabama Crimson',
	'Alabaster',
	'Alice Blue',
	'Alien Armpit',
	'Alizarin Crimson',
	'Alloy Orange',
	'Almond',
	'Amaranth',
	'Amaranth Deep Purple',
	'Amaranth Pink',
	'Amaranth Purple',
	'Amaranth Red',
	'Amazon Store',
	'Amazonite',
	'Amber',
	'Amber (SAE/ECE)',
	'American Rose',
	'Amethyst',
	'Android Green',
	'Anti-Flash White',
	'Antique Brass',
	'Antique Bronze',
	'Antique Fuchsia',
	'Antique Ruby',
	'Antique White',
	'Ao (English)',
	'Apple Green',
	'Apricot',
	'Aqua',
	'Aquamarine',
	'Arctic Lime',
	'Army Green',
	'Arsenic',
	'Artichoke',
	'Arylide Yellow',
	'Ash Gray',
	'Asparagus',
	'Atomic Tangerine',
	'Auburn',
	'Aureolin',
	'AuroMetalSaurus',
	'Avocado',
	'Awesome',
	'Aztec Gold',
	'Azure',
	'Azure (Web Color)',
	'Azure Mist',
	'Azureish White',
	'Baby Blue',
	'Baby Blue Eyes',
	'Baby Pink',
	'Baby Powder',
	'Baker-Miller Pink',
	'Ball Blue',
	'Banana Mania',
	'Banana Yellow',
	'Bangladesh Green',
	'Barbie Pink',
	'Barn Red',
	'Battery Charged Blue',
	'Battleship Grey',
	'Bazaar',
	'Beau Blue',
	'Beaver',
	'Begonia',
	'Beige',
	"B'dazzled Blue",
	"Big Dip O'ruby",
	'Big Foot Feet',
	'Bisque',
	'Bistre',
	'Bistre Brown',
	'Bitter Lemon',
	'Bitter Lime',
	'Bittersweet',
	'Bittersweet Shimmer',
	'Black',
	'Black Bean',
	'Black Coral',
	'Black Leather Jacket',
	'Black Olive',
	'Black Shadows',
	'Blanched Almond',
	'Blast-Off Bronze',
	'Bleu De France',
	'Blizzard Blue',
	'Blond',
	'Blue',
	'Blue (Crayola)',
	'Blue (Munsell)',
	'Blue (NCS)',
	'Blue (Pantone)',
	'Blue (Pigment)',
	'Blue (RYB)',
	'Blue Bell',
	'Blue Bolt',
	'Blue-Gray',
	'Blue-Green',
	'Blue Jeans',
	'Blue Lagoon',
	'Blue-Magenta Violet',
	'Blue Sapphire',
	'Blue-Violet',
	'Blue Yonder',
	'Blueberry',
	'Bluebonnet',
	'Blush',
	'Bole',
	'Bondi Blue',
	'Bone',
	'Booger Buster',
	'Boston University Red',
	'Bottle Green',
	'Boysenberry',
	'Brandeis Blue',
	'Brass',
	'Brick Red',
	'Bright Cerulean',
	'Bright Green',
	'Bright Lavender',
	'Bright Lilac',
	'Bright Maroon',
	'Bright Navy Blue',
	'Bright Pink',
	'Bright Turquoise',
	'Bright Ube',
	'Bright Yellow (Crayola)',
	'Brilliant Azure',
	'Brilliant Lavender',
	'Brilliant Rose',
	'Brink Pink',
	'British Racing Green',
	'Bronze',
	'Bronze Yellow',
	'Brown (Traditional)',
	'Brown (Web)',
	'Brown-Nose',
	'Brown Sugar',
	'Brown Yellow',
	'Brunswick Green',
	'Bubble Gum',
	'Bubbles',
	'Bud Green',
	'Buff',
	'Bulgarian Rose',
	'Burgundy',
	'Burlywood',
	'Burnished Brown',
	'Burnt Orange',
	'Burnt Sienna',
	'Burnt Umber',
	'Button Blue',
	'Byzantine',
	'Byzantium',
	'Cadet',
	'Cadet Blue',
	'Cadet Grey',
	'Cadmium Green',
	'Cadmium Orange',
	'Cadmium Red',
	'Cadmium Yellow',
	'Cafe Au Lait',
	'Cafe Noir',
	'Cal Poly Pomona Green',
	'Cambridge Blue',
	'Camel',
	'Cameo Pink',
	'Camouflage Green',
	'Canary',
	'Canary Yellow',
	'Candy Apple Red',
	'Candy Pink',
	'Capri',
	'Caput Mortuum',
	'Cardinal',
	'Caribbean Green',
	'Carmine',
	'Carmine (M&P)',
	'Carmine Pink',
	'Carmine Red',
	'Carnation Pink',
	'Carnelian',
	'Carolina Blue',
	'Carrot Orange',
	'Castleton Green',
	'Catalina Blue',
	'Catawba',
	'Cedar Chest',
	'Ceil',
	'Celadon',
	'Celadon Blue',
	'Celadon Green',
	'Celeste',
	'Celestial Blue',
	'Cerise',
	'Cerise Pink',
	'Cerulean',
	'Cerulean Blue',
	'Cerulean Frost',
	'CG Blue',
	'CG Red',
	'Chamoisee',
	'Champagne',
	'Champagne Pink',
	'Charcoal',
	'Charleston Green',
	'Charm Pink',
	'Chartreuse (Traditional)',
	'Chartreuse (Web)',
	'Cherry',
	'Cherry Blossom Pink',
	'Chestnut',
	'China Pink',
	'China Rose',
	'Chinese Red',
	'Chinese Violet',
	'Chlorophyll Green',
	'Chocolate (Traditional)',
	'Chocolate (Web)',
	'Chrome Yellow',
	'Cinereous',
	'Cinnabar',
	'Cinnamon',
	'Cinnamon Satin',
	'Citrine',
	'Citron',
	'Claret',
	'Classic Rose',
	'Cobalt Blue',
	'Cocoa Brown',
	'Coconut',
	'Coffee',
	'Columbia Blue',
	'Congo Pink',
	'Cool Black',
	'Cool Grey',
	'Copper',
	'Copper (Crayola)',
	'Copper Penny',
	'Copper Red',
	'Copper Rose',
	'Coquelicot',
	'Coral',
	'Coral Pink',
	'Coral Red',
	'Coral Reef',
	'Cordovan',
	'Corn',
	'Cornell Red',
	'Cornflower Blue',
	'Cornsilk',
	'Cosmic Cobalt',
	'Cosmic Latte',
	'Coyote Brown',
	'Cotton Candy',
	'Cream',
	'Crimson',
	'Crimson Glory',
	'Crimson Red',
	'Cultured',
	'Cyan',
	'Cyan Azure',
	'Cyan-Blue Azure',
	'Cyan Cobalt Blue',
	'Cyan Cornflower Blue',
	'Cyan (Process)',
	'Cyber Grape',
	'Cyber Yellow',
	'Cyclamen',
	'Daffodil',
	'Dandelion',
	'Dark Blue',
	'Dark Blue-Gray',
	'Dark Brown',
	'Dark Brown-Tangelo',
	'Dark Byzantium',
	'Dark Candy Apple Red',
	'Dark Cerulean',
	'Dark Chestnut',
	'Dark Coral',
	'Dark Cyan',
	'Dark Electric Blue',
	'Dark Goldenrod',
	'Dark Gray (X11)',
	'Dark Green',
	'Dark Green (X11)',
	'Dark Gunmetal',
	'Dark Imperial Blue',
	'Dark Imperial Blue',
	'Dark Jungle Green',
	'Dark Khaki',
	'Dark Lava',
	'Dark Lavender',
	'Dark Liver',
	'Dark Liver (Horses)',
	'Dark Magenta',
	'Dark Medium Gray',
	'Dark Midnight Blue',
	'Dark Moss Green',
	'Dark Olive Green',
	'Dark Orange',
	'Dark Orchid',
	'Dark Pastel Blue',
	'Dark Pastel Green',
	'Dark Pastel Purple',
	'Dark Pastel Red',
	'Dark Pink',
	'Dark Powder Blue',
	'Dark Puce',
	'Dark Purple',
	'Dark Raspberry',
	'Dark Red',
	'Dark Salmon',
	'Dark Scarlet',
	'Dark Sea Green',
	'Dark Sienna',
	'Dark Sky Blue',
	'Dark Slate Blue',
	'Dark Slate Gray',
	'Dark Spring Green',
	'Dark Tan',
	'Dark Tangerine',
	'Dark Taupe',
	'Dark Terra Cotta',
	'Dark Turquoise',
	'Dark Vanilla',
	'Dark Violet',
	'Dark Yellow',
	'Dartmouth Green',
	"Davy's Grey",
	'Debian Red',
	'Deep Aquamarine',
	'Deep Carmine',
	'Deep Carmine Pink',
	'Deep Carrot Orange',
	'Deep Cerise',
	'Deep Champagne',
	'Deep Chestnut',
	'Deep Coffee',
	'Deep Fuchsia',
	'Deep Green',
	'Deep Green-Cyan Turquoise',
	'Deep Jungle Green',
	'Deep Koamaru',
	'Deep Lemon',
	'Deep Lilac',
	'Deep Magenta',
	'Deep Maroon',
	'Deep Mauve',
	'Deep Moss Green',
	'Deep Peach',
	'Deep Pink',
	'Deep Puce',
	'Deep Red',
	'Deep Ruby',
	'Deep Saffron',
	'Deep Sky Blue',
	'Deep Space Sparkle',
	'Deep Spring Bud',
	'Deep Taupe',
	'Deep Tuscan Red',
	'Deep Violet',
	'Deer',
	'Denim',
	'Denim Blue',
	'Desaturated Cyan',
	'Desert',
	'Desert Sand',
	'Desire',
	'Diamond',
	'Dim Gray',
	'Dingy Dungeon',
	'Dirt',
	'Dodger Blue',
	'Dodie Yellow',
	'Dogwood Rose',
	'Dollar Bill',
	'Dolphin Gray',
	'Donkey Brown',
	'Drab',
	'Duke Blue',
	'Dust Storm',
	'Dutch White',
	'Earth Yellow',
	'Ebony',
	'Ecru',
	'Eerie Black',
	'Eggplant',
	'Eggshell',
	'Egyptian Blue',
	'Electric Blue',
	'Electric Crimson',
	'Electric Cyan',
	'Electric Green',
	'Electric Indigo',
	'Electric Lavender',
	'Electric Lime',
	'Electric Purple',
	'Electric Ultramarine',
	'Electric Violet',
	'Electric Yellow',
	'Emerald',
	'Eminence',
	'English Green',
	'English Lavender',
	'English Red',
	'English Vermillion',
	'English Violet',
	'Eton Blue',
	'Eucalyptus',
	'Fallow',
	'Falu Red',
	'Fandango',
	'Fandango Pink',
	'Fashion Fuchsia',
	'Fawn',
	'Feldgrau',
	'Feldspar',
	'Fern Green',
	'Ferrari Red',
	'Field Drab',
	'Fiery Rose',
	'Firebrick',
	'Fire Engine Red',
	'Flame',
	'Flamingo Pink',
	'Flattery',
	'Flavescent',
	'Flax',
	'Flirt',
	'Floral White',
	'Fluorescent Orange',
	'Fluorescent Pink',
	'Fluorescent Yellow',
	'Folly',
	'Forest Green (Traditional)',
	'Forest Green (Web)',
	'French Beige',
	'French Bistre',
	'French Blue',
	'French Fuchsia',
	'French Lilac',
	'French Lime',
	'French Mauve',
	'French Pink',
	'French Plum',
	'French Puce',
	'French Raspberry',
	'French Rose',
	'French Sky Blue',
	'French Violet',
	'French Wine',
	'Fresh Air',
	'Frogert',
	'Fuchsia',
	'Fuchsia (Crayola)',
	'Fuchsia Pink',
	'Fuchsia Purple',
	'Fuchsia Rose',
	'Fulvous',
	'Fuzzy Wuzzy',
	'Gainsboro',
	'Gamboge',
	'Gamboge Orange (Brown)',
	'Gargoyle Gas',
	'Generic Viridian',
	'Ghost White',
	"Giant's Club",
	'Giants Orange',
	'Ginger',
	'Glaucous',
	'Glitter',
	'Glossy Grape',
	'GO Green',
	'Gold (Metallic)',
	'Gold (Web) (Golden)',
	'Gold Fusion',
	'Golden Brown',
	'Golden Poppy',
	'Golden Yellow',
	'Goldenrod',
	'Granite Gray',
	'Granny Smith Apple',
	'Grape',
	'Gray',
	'Gray (HTML/CSS Gray)',
	'Gray (X11 Gray)',
	'Gray-Asparagus',
	'Gray-Blue',
	'Green (Color Wheel) (X11 Green)',
	'Green (Crayola)',
	'Green (HTML/CSS Color)',
	'Green (Munsell)',
	'Green (NCS)',
	'Green (Pantone)',
	'Green (Pigment)',
	'Green (RYB)',
	'Green-Blue',
	'Green-Cyan',
	'Green Lizard',
	'Green Sheen',
	'Green-Yellow',
	'Grizzly',
	'Grullo',
	'Guppie Green',
	'Gunmetal',
	'Halaya Ube',
	'Han Blue',
	'Han Purple',
	'Hansa Yellow',
	'Harlequin',
	'Harlequin Green',
	'Harvard Crimson',
	'Harvest Gold',
	'Heart Gold',
	'Heat Wave',
	'Heidelberg Red',
	'Heliotrope',
	'Heliotrope Gray',
	'Heliotrope Magenta',
	'Hollywood Cerise',
	'Honeydew',
	'Honolulu Blue',
	"Hooker's Green",
	'Hot Magenta',
	'Hot Pink',
	'Hunter Green',
	'Iceberg',
	'Icterine',
	'Iguana Green',
	'Illuminating Emerald',
	'Imperial',
	'Imperial Blue',
	'Imperial Purple',
	'Imperial Red',
	'Inchworm',
	'Independence',
	'India Green',
	'Indian Red',
	'Indian Yellow',
	'Indigo',
	'Indigo Dye',
	'Indigo (Web)',
	'Infra Red',
	'Interdimensional Blue',
	'International Klein Blue',
	'International Orange (Aerospace)',
	'International Orange (Engineering)',
	'International Orange (Golden Gate Bridge)',
	'Iris',
	'Irresistible',
	'Isabelline',
	'Islamic Green',
	'Italian Sky Blue',
	'Ivory',
	'Jade',
	'Japanese Carmine',
	'Japanese Indigo',
	'Japanese Violet',
	'Jasmine',
	'Jasper',
	'Jazzberry Jam',
	'Jelly Bean',
	'Jet',
	'Jonquil',
	'Jordy Blue',
	'June Bud',
	'Jungle Green',
	'Kelly Green',
	'Kenyan Copper',
	'Keppel',
	'Key Lime',
	'Khaki (HTML/CSS) (Khaki)',
	'Khaki (X11) (Light Khaki)',
	'Kiwi',
	'Kobe',
	'Kobi',
	'Kobicha',
	'Kombu Green',
	'KSU Purple',
	'KU Crimson',
	'La Salle Green',
	'Languid Lavender',
	'Lapis Lazuli',
	'Laser Lemon',
	'Laurel Green',
	'Lava',
	'Lavender (Floral)',
	'Lavender (Web)',
	'Lavender Blue',
	'Lavender Blush',
	'Lavender Gray',
	'Lavender Indigo',
	'Lavender Magenta',
	'Lavender Mist',
	'Lavender Pink',
	'Lavender Purple',
	'Lavender Rose',
	'Lawn Green',
	'Lemon',
	'Lemon Chiffon',
	'Lemon Curry',
	'Lemon Glacier',
	'Lemon Lime',
	'Lemon Meringue',
	'Lemon Yellow',
	'Licorice',
	'Liberty',
	'Light Apricot',
	'Light Blue',
	'Light Brown',
	'Light Carmine Pink',
	'Light Cobalt Blue',
	'Light Coral',
	'Light Cornflower Blue',
	'Light Crimson',
	'Light Cyan',
	'Light Deep Pink',
	'Light French Beige',
	'Light Fuchsia Pink',
	'Light Goldenrod Yellow',
	'Light Gray',
	'Light Grayish Magenta',
	'Light Green',
	'Light Hot Pink',
	'Light Khaki',
	'Light Medium Orchid',
	'Light Moss Green',
	'Light Orange',
	'Light Orchid',
	'Light Pastel Purple',
	'Light Pink',
	'Light Red Ochre',
	'Light Salmon',
	'Light Salmon Pink',
	'Light Sea Green',
	'Light Sky Blue',
	'Light Slate Gray',
	'Light Steel Blue',
	'Light Taupe',
	'Light Thulian Pink',
	'Light Yellow',
	'Lilac',
	'Lilac Luster',
	'Lime (Color Wheel)',
	'Lime (Web) (X11 Green)',
	'Lime Green',
	'Limerick',
	'Lincoln Green',
	'Linen',
	'Loeen (Lopen) Look',
	'Liseran Purple',
	'Little Boy Blue',
	'Liver',
	'Liver (Dogs)',
	'Liver (Organ)',
	'Liver Chestnut',
	'Livid',
	'Lumber',
	'Lust',
	'Maastricht Blue',
	'Macaroni And Cheese',
	'Madder Lake',
	'Magenta',
	'Magenta (Crayola)',
	'Magenta (Dye)',
	'Magenta (Pantone)',
	'Magenta (Process)',
	'Magenta Haze',
	'Magenta-Pink',
	'Magic Mint',
	'Magic Potion',
	'Magnolia',
	'Mahogany',
	'Maize',
	'Majorelle Blue',
	'Malachite',
	'Manatee',
	'Mandarin',
	'Mango Tango',
	'Mantis',
	'Mardi Gras',
	'Marigold',
	'Maroon (Crayola)',
	'Maroon (HTML/CSS)',
	'Maroon (X11)',
	'Mauve',
	'Mauve Taupe',
	'Mauvelous',
	'Maximum Blue',
	'Maximum Blue Green',
	'Maximum Blue Purple',
	'Maximum Green',
	'Maximum Green Yellow',
	'Maximum Purple',
	'Maximum Red',
	'Maximum Red Purple',
	'Maximum Yellow',
	'Maximum Yellow Red',
	'May Green',
	'Maya Blue',
	'Meat Brown',
	'Medium Aquamarine',
	'Medium Blue',
	'Medium Candy Apple Red',
	'Medium Carmine',
	'Medium Champagne',
	'Medium Electric Blue',
	'Medium Jungle Green',
	'Medium Lavender Magenta',
	'Medium Orchid',
	'Medium Persian Blue',
	'Medium Purple',
	'Medium Red-Violet',
	'Medium Ruby',
	'Medium Sea Green',
	'Medium Sky Blue',
	'Medium Slate Blue',
	'Medium Spring Bud',
	'Medium Spring Green',
	'Medium Taupe',
	'Medium Turquoise',
	'Medium Tuscan Red',
	'Medium Vermilion',
	'Medium Violet-Red',
	'Mellow Apricot',
	'Mellow Yellow',
	'Melon',
	'Metallic Seaweed',
	'Metallic Sunburst',
	'Mexican Pink',
	'Middle Blue',
	'Middle Blue Green',
	'Middle Blue Purple',
	'Middle Red Purple',
	'Middle Green',
	'Middle Green Yellow',
	'Middle Purple',
	'Middle Red',
	'Middle Red Purple',
	'Middle Yellow',
	'Middle Yellow Red',
	'Midnight',
	'Midnight Blue',
	'Midnight Green (Eagle Green)',
	'Mikado Yellow',
	'Milk',
	'Mimi Pink',
	'Mindaro',
	'Ming',
	'Minion Yellow',
	'Mint',
	'Mint Cream',
	'Mint Green',
	'Misty Moss',
	'Misty Rose',
	'Moccasin',
	'Mode Beige',
	'Moonstone Blue',
	'Mordant Red 19',
	'Morning Blue',
	'Moss Green',
	'Mountain Meadow',
	'Mountbatten Pink',
	'MSU Green',
	'Mughal Green',
	'Mulberry',
	"Mummy's Tomb",
	'Mustard',
	'Myrtle Green',
	'Mystic',
	'Mystic Maroon',
	'Nadeshiko Pink',
	'Napier Green',
	'Naples Yellow',
	'Navajo White',
	'Navy',
	'Navy Purple',
	'Neon Carrot',
	'Neon Fuchsia',
	'Neon Green',
	'New Car',
	'New York Pink',
	'Nickel',
	'Non-Photo Blue',
	'North Texas Green',
	'Nyanza',
	'Ocean Blue',
	'Ocean Boat Blue',
	'Ocean Green',
	'Ochre',
	'Office Green',
	'Ogre Odor',
	'Old Burgundy',
	'Old Gold',
	'Old Heliotrope',
	'Old Lace',
	'Old Lavender',
	'Old Mauve',
	'Old Moss Green',
	'Old Rose',
	'Old Silver',
	'Olive',
	'Olive Drab (#3)',
	'Olive Drab #7',
	'Olivine',
	'Onyx',
	'Opera Mauve',
	'Orange (Color Wheel)',
	'Orange (Crayola)',
	'Orange (Pantone)',
	'Orange (RYB)',
	'Orange (Web)',
	'Orange Peel',
	'Orange-Red',
	'Orange Soda',
	'Orange-Yellow',
	'Orchid',
	'Orchid Pink',
	'Orioles Orange',
	'Otter Brown',
	'Outer Space',
	'Outrageous Orange',
	'Oxford Blue',
	'OU Crimson Red',
	'Pacific Blue',
	'Pakistan Green',
	'Palatinate Blue',
	'Palatinate Purple',
	'Pale Aqua',
	'Pale Blue',
	'Pale Brown',
	'Pale Carmine',
	'Pale Cerulean',
	'Pale Chestnut',
	'Pale Copper',
	'Pale Cornflower Blue',
	'Pale Cyan',
	'Pale Gold',
	'Pale Goldenrod',
	'Pale Green',
	'Pale Lavender',
	'Pale Magenta',
	'Pale Magenta-Pink',
	'Pale Pink',
	'Pale Plum',
	'Pale Red-Violet',
	'Pale Robin Egg Blue',
	'Pale Silver',
	'Pale Spring Bud',
	'Pale Taupe',
	'Pale Turquoise',
	'Pale Violet',
	'Pale Violet-Red',
	'Palm Leaf',
	'Pansy Purple',
	'Paolo Veronese Green',
	'Papaya Whip',
	'Paradise Pink',
	'Paris Green',
	'Parrot Pink',
	'Pastel Blue',
	'Pastel Brown',
	'Pastel Gray',
	'Pastel Green',
	'Pastel Magenta',
	'Pastel Orange',
	'Pastel Pink',
	'Pastel Purple',
	'Pastel Red',
	'Pastel Violet',
	'Pastel Yellow',
	'Patriarch',
	"Payne's Grey",
	'Peach',
	'Peach',
	'Peach-Orange',
	'Peach Puff',
	'Peach-Yellow',
	'Pear',
	'Pearl',
	'Pearl Aqua',
	'Pearly Purple',
	'Peridot',
	'Periwinkle',
	'Permanent Geranium Lake',
	'Persian Blue',
	'Persian Green',
	'Persian Indigo',
	'Persian Orange',
	'Persian Pink',
	'Persian Plum',
	'Persian Red',
	'Persian Rose',
	'Persimmon',
	'Peru',
	'Pewter Blue',
	'Phlox',
	'Phthalo Blue',
	'Phthalo Green',
	'Picton Blue',
	'Pictorial Carmine',
	'Piggy Pink',
	'Pine Green',
	'Pineapple',
	'Pink',
	'Pink (Pantone)',
	'Pink Flamingo',
	'Pink Lace',
	'Pink Lavender',
	'Pink-Orange',
	'Pink Pearl',
	'Pink Raspberry',
	'Pink Sherbet',
	'Pistachio',
	'Pixie Powder',
	'Platinum',
	'Plum',
	'Plum (Web)',
	'Plump Purple',
	'Polished Pine',
	'Pomp And Power',
	'Popstar',
	'Portland Orange',
	'Powder Blue',
	'Princess Perfume',
	'Princeton Orange',
	'Prune',
	'Prussian Blue',
	'Psychedelic Purple',
	'Puce',
	'Puce Red',
	'Pullman Brown (UPS Brown)',
	'Pullman Green',
	'Pumpkin',
	'Purple (HTML)',
	'Purple (Munsell)',
	'Purple (X11)',
	'Purple Heart',
	'Purple Mountain Majesty',
	'Purple Navy',
	'Purple Pizzazz',
	'Purple Plum',
	'Purple Taupe',
	'Purpureus',
	'Quartz',
	'Queen Blue',
	'Queen Pink',
	'Quick Silver',
	'Quinacridone Magenta',
	'Rackley',
	'Radical Red',
	'Raisin Black',
	'Rajah',
	'Raspberry',
	'Raspberry Glace',
	'Raspberry Pink',
	'Raspberry Rose',
	'Raw Sienna',
	'Raw Umber',
	'Razzle Dazzle Rose',
	'Razzmatazz',
	'Razzmic Berry',
	'Rebecca Purple',
	'Red',
	'Red (Crayola)',
	'Red (Munsell)',
	'Red (NCS)',
	'Red (Pantone)',
	'Red (Pigment)',
	'Red (RYB)',
	'Red-Brown',
	'Red Devil',
	'Red-Orange',
	'Red-Purple',
	'Red Salsa',
	'Red-Violet',
	'Redwood',
	'Regalia',
	'Registration Black',
	'Resolution Blue',
	'Rhythm',
	'Rich Black',
	'Rich Black (FOGRA29)',
	'Rich Black (FOGRA39)',
	'Rich Brilliant Lavender',
	'Rich Carmine',
	'Rich Electric Blue',
	'Rich Lavender',
	'Rich Lilac',
	'Rich Maroon',
	'Rifle Green',
	'Roast Coffee',
	'Robin Egg Blue',
	'Rocket Metallic',
	'Roman Silver',
	'Rose',
	'Rose Bonbon',
	'Rose Dust',
	'Rose Ebony',
	'Rose Gold',
	'Rose Madder',
	'Rose Pink',
	'Rose Quartz',
	'Rose Red',
	'Rose Taupe',
	'Rose Vale',
	'Rosewood',
	'Rosso Corsa',
	'Rosy Brown',
	'Royal Azure',
	'Royal Blue',
	'Royal Blue',
	'Royal Fuchsia',
	'Royal Purple',
	'Royal Yellow',
	'Ruber',
	'Rubine Red',
	'Ruby',
	'Ruby Red',
	'Ruddy',
	'Ruddy Brown',
	'Ruddy Pink',
	'Rufous',
	'Russet',
	'Russian Green',
	'Russian Violet',
	'Rust',
	'Rusty Red',
	'Sacramento State Green',
	'Saddle Brown',
	'Safety Orange',
	'Safety Orange (Blaze Orange)',
	'Safety Yellow',
	'Saffron',
	'Sage',
	"St. Patrick's Blue",
	'Salmon',
	'Salmon Pink',
	'Sand',
	'Sand Dune',
	'Sandstorm',
	'Sandy Brown',
	'Sandy Tan',
	'Sandy Taupe',
	'Sangria',
	'Sap Green',
	'Sapphire',
	'Sapphire Blue',
	'Sasquatch Socks',
	'Satin Sheen Gold',
	'Scarlet',
	'Scarlet',
	'Schauss Pink',
	'School Bus Yellow',
	"Screamin' Green",
	'Sea Blue',
	'Sea Foam Green',
	'Sea Green',
	'Sea Serpent',
	'Seal Brown',
	'Seashell',
	'Selective Yellow',
	'Sepia',
	'Shadow',
	'Shadow Blue',
	'Shampoo',
	'Shamrock Green',
	'Sheen Green',
	'Shimmering Blush',
	'Shiny Shamrock',
	'Shocking Pink',
	'Shocking Pink (Crayola)',
	'Sienna',
	'Silver',
	'Silver Chalice',
	'Silver Lake Blue',
	'Silver Pink',
	'Silver Sand',
	'Sinopia',
	'Sizzling Red',
	'Sizzling Sunrise',
	'Skobeloff',
	'Sky Blue',
	'Sky Magenta',
	'Slate Blue',
	'Slate Gray',
	'Smalt (Dark Powder Blue)',
	'Slimy Green',
	'Smashed Pumpkin',
	'Smitten',
	'Smoke',
	'Smokey Topaz',
	'Smoky Black',
	'Smoky Topaz',
	'Snow',
	'Soap',
	'Solid Pink',
	'Sonic Silver',
	'Spartan Crimson',
	'Space Cadet',
	'Spanish Bistre',
	'Spanish Blue',
	'Spanish Carmine',
	'Spanish Crimson',
	'Spanish Gray',
	'Spanish Green',
	'Spanish Orange',
	'Spanish Pink',
	'Spanish Red',
	'Spanish Sky Blue',
	'Spanish Violet',
	'Spanish Viridian',
	'Spicy Mix',
	'Spiro Disco Ball',
	'Spring Bud',
	'Spring Frost',
	'Spring Green',
	'Star Command Blue',
	'Steel Blue',
	'Steel Pink',
	'Steel Teal',
	'Stil De Grain Yellow',
	'Stizza',
	'Stormcloud',
	'Straw',
	'Strawberry',
	'Sugar Plum',
	'Sunburnt Cyclops',
	'Sunglow',
	'Sunny',
	'Sunray',
	'Sunset',
	'Sunset Orange',
	'Super Pink',
	'Sweet Brown',
	'Tan',
	'Tangelo',
	'Tangerine',
	'Tangerine Yellow',
	'Tango Pink',
	'Tart Orange',
	'Taupe',
	'Taupe Gray',
	'Tea Green',
	'Tea Rose',
	'Tea Rose',
	'Teal',
	'Teal Blue',
	'Teal Deer',
	'Teal Green',
	'Telemagenta',
	'Tenne (Tawny)',
	'Terra Cotta',
	'Thistle',
	'Thulian Pink',
	'Tickle Me Pink',
	'Tiffany Blue',
	"Tiger's Eye",
	'Timberwolf',
	'Titanium Yellow',
	'Tomato',
	'Toolbox',
	'Topaz',
	'Tractor Red',
	'Trolley Grey',
	'Tropical Rain Forest',
	'Tropical Violet',
	'True Blue',
	'Tufts Blue',
	'Tulip',
	'Tumbleweed',
	'Turkish Rose',
	'Turquoise',
	'Turquoise Blue',
	'Turquoise Green',
	'Turquoise Surf',
	'Turtle Green',
	'Tuscan',
	'Tuscan Brown',
	'Tuscan Red',
	'Tuscan Tan',
	'Tuscany',
	'Twilight Lavender',
	'Tyrian Purple',
	'UA Blue',
	'UA Red',
	'Ube',
	'UCLA Blue',
	'UCLA Gold',
	'UFO Green',
	'Ultramarine',
	'Ultramarine Blue',
	'Ultra Pink',
	'Ultra Red',
	'Umber',
	'Unbleached Silk',
	'United Nations Blue',
	'University Of California Gold',
	'Unmellow Yellow',
	'UP Forest Green',
	'UP Maroon',
	'Upsdell Red',
	'Urobilin',
	'USAFA Blue',
	'USC Cardinal',
	'USC Gold',
	'University Of Tennessee Orange',
	'Utah Crimson',
	'Van Dyke Brown',
	'Vanilla',
	'Vanilla Ice',
	'Vegas Gold',
	'Venetian Red',
	'Verdigris',
	'Vermilion',
	'Vermilion',
	'Veronica',
	'Very Light Azure',
	'Very Light Blue',
	'Very Light Malachite Green',
	'Very Light Tangelo',
	'Very Pale Orange',
	'Very Pale Yellow',
	'Violet',
	'Violet (Color Wheel)',
	'Violet (RYB)',
	'Violet (Web)',
	'Violet-Blue',
	'Violet-Red',
	'Viridian',
	'Viridian Green',
	'Vista Blue',
	'Vivid Amber',
	'Vivid Auburn',
	'Vivid Burgundy',
	'Vivid Cerise',
	'Vivid Cerulean',
	'Vivid Crimson',
	'Vivid Gamboge',
	'Vivid Lime Green',
	'Vivid Malachite',
	'Vivid Mulberry',
	'Vivid Orange',
	'Vivid Orange Peel',
	'Vivid Orchid',
	'Vivid Raspberry',
	'Vivid Red',
	'Vivid Red-Tangelo',
	'Vivid Sky Blue',
	'Vivid Tangelo',
	'Vivid Tangerine',
	'Vivid Vermilion',
	'Vivid Violet',
	'Vivid Yellow',
	'Volt',
	'Wageningen Green',
	'Warm Black',
	'Waterspout',
	'Weldon Blue',
	'Wenge',
	'Wheat',
	'White',
	'White Smoke',
	'Wild Blue Yonder',
	'Wild Orchid',
	'Wild Strawberry',
	'Wild Watermelon',
	'Willpower Orange',
	'Windsor Tan',
	'Wine',
	'Wine Dregs',
	'Winter Sky',
	'Winter Wizard',
	'Wintergreen Dream',
	'Wisteria',
	'Wood Brown',
	'Xanadu',
	'Yale Blue',
	'Yankees Blue',
	'Yellow',
	'Yellow (Crayola)',
	'Yellow (Munsell)',
	'Yellow (NCS)',
	'Yellow (Pantone)',
	'Yellow (Process)',
	'Yellow (RYB)',
	'Yellow-Green',
	'Yellow Orange',
	'Yellow Rose',
	'Yellow Sunshine',
	'Zaffre',
	'Zinnwaldite Brown',
	'Zomp'
];

export const vehicleModels = [
	'Alhambra',
	'Altea',
	'Altea XL',
	'Arosa',
	'Cordoba',
	'Cordoba Vario',
	'Exeo',
	'Ibiza',
	'Ibiza ST',
	'Exeo ST',
	'Leon',
	'Leon ST',
	'Inca',
	'Mii',
	'Toledo',
	'Captur',
	'Clio',
	'Clio Grandtour',
	'Espace',
	'Express',
	'Fluence',
	'Grand Espace',
	'Grand Modus',
	'Grand Scenic',
	'Kadjar',
	'Kangoo',
	'Kangoo Express',
	'Koleos',
	'Laguna',
	'Laguna Grandtour',
	'Latitude',
	'Mascott',
	'Mégane',
	'Mégane CC',
	'Mégane Combi',
	'Mégane Grandtour',
	'Mégane Coupé',
	'Mégane Scénic',
	'Scénic',
	'Talisman',
	'Talisman Grandtour',
	'Thalia',
	'Twingo',
	'Wind',
	'Zoé',
	'1007',
	'107',
	'106',
	'108',
	'2008',
	'205',
	'205 Cabrio',
	'206',
	'206 CC',
	'206 SW',
	'207',
	'207 CC',
	'207 SW',
	'306',
	'307',
	'307 CC',
	'307 SW',
	'308',
	'308 CC',
	'308 SW',
	'309',
	'4007',
	'4008',
	'405',
	'406',
	'407',
	'407 SW',
	'5008',
	'508',
	'508 SW',
	'605',
	'806',
	'607',
	'807',
	'Bipper',
	'RCZ',
	'Dokker',
	'Duster',
	'Lodgy',
	'Logan',
	'Logan MCV',
	'Logan Van',
	'Sandero',
	'Solenza',
	'Berlingo',
	'C-Crosser',
	'C-Elissée',
	'C-Zero',
	'C1',
	'C2',
	'C3',
	'C3 Picasso',
	'C4',
	'C4 Aircross',
	'C4 Cactus',
	'C4 Coupé',
	'C4 Grand Picasso',
	'C4 Sedan',
	'C5',
	'C5 Break',
	'C5 Tourer',
	'C6',
	'C8',
	'DS3',
	'DS4',
	'DS5',
	'Evasion',
	'Jumper',
	'Jumpy',
	'Saxo',
	'Nemo',
	'Xantia',
	'Xsara',
	'Agila',
	'Ampera',
	'Antara',
	'Astra',
	'Astra cabrio',
	'Astra caravan',
	'Astra coupé',
	'Calibra',
	'Campo',
	'Cascada',
	'Corsa',
	'Frontera',
	'Insignia',
	'Insignia kombi',
	'Kadett',
	'Meriva',
	'Mokka',
	'Movano',
	'Omega',
	'Signum',
	'Vectra',
	'Vectra Caravan',
	'Vivaro',
	'Vivaro Kombi',
	'Zafira',
	'145',
	'146',
	'147',
	'155',
	'156',
	'156 Sportwagon',
	'159',
	'159 Sportwagon',
	'164',
	'166',
	'4C',
	'Brera',
	'GTV',
	'MiTo',
	'Crosswagon',
	'Spider',
	'GT',
	'Giulietta',
	'Giulia',
	'Favorit',
	'Felicia',
	'Citigo',
	'Fabia',
	'Fabia Combi',
	'Fabia Sedan',
	'Felicia Combi',
	'Octavia',
	'Octavia Combi',
	'Roomster',
	'Yeti',
	'Rapid',
	'Rapid Spaceback',
	'Superb',
	'Superb Combi',
	'Alero',
	'Aveo',
	'Camaro',
	'Captiva',
	'Corvette',
	'Cruze',
	'Cruze SW',
	'Epica',
	'Equinox',
	'Evanda',
	'HHR',
	'Kalos',
	'Lacetti',
	'Lacetti SW',
	'Lumina',
	'Malibu',
	'Matiz',
	'Monte Carlo',
	'Nubira',
	'Orlando',
	'Spark',
	'Suburban',
	'Tacuma',
	'Tahoe',
	'Trax',
	'911 Carrera',
	'911 Carrera Cabrio',
	'911 Targa',
	'911 Turbo',
	'924',
	'944',
	'997',
	'Boxster',
	'Cayenne',
	'Cayman',
	'Macan',
	'Panamera',
	'Accord',
	'Accord Coupé',
	'Accord Tourer',
	'City',
	'Civic',
	'Civic Aerodeck',
	'Civic Coupé',
	'Civic Tourer',
	'Civic Type R',
	'CR-V',
	'CR-X',
	'CR-Z',
	'FR-V',
	'HR-V',
	'Insight',
	'Integra',
	'Jazz',
	'Legend',
	'Prelude',
	'BRZ',
	'Forester',
	'Impreza',
	'Impreza Wagon',
	'Justy',
	'Legacy',
	'Legacy Wagon',
	'Legacy Outback',
	'Levorg',
	'Outback',
	'SVX',
	'Tribeca',
	'Tribeca B9',
	'XV',
	'121',
	'2',
	'3',
	'323',
	'323 Combi',
	'323 Coupé',
	'323 F',
	'5',
	'6',
	'6 Combi',
	'626',
	'626 Combi',
	'B-Fighter',
	'B2500',
	'BT',
	'CX-3',
	'CX-5',
	'CX-7',
	'CX-9',
	'Demio',
	'MPV',
	'MX-3',
	'MX-5',
	'MX-6',
	'Premacy',
	'RX-7',
	'RX-8',
	'Xedox 6',
	'3000 GT',
	'ASX',
	'Carisma',
	'Colt',
	'Colt CC',
	'Eclipse',
	'Fuso canter',
	'Galant',
	'Galant Combi',
	'Grandis',
	'L200',
	'L200 Pick up',
	'L200 Pick up Allrad',
	'L300',
	'Lancer',
	'Lancer Combi',
	'Lancer Evo',
	'Lancer Sportback',
	'Outlander',
	'Pajero',
	'Pajeto Pinin',
	'Pajero Pinin Wagon',
	'Pajero Sport',
	'Pajero Wagon',
	'Space Star',
	'CT',
	'GS',
	'GS 300',
	'GX',
	'IS',
	'IS 200',
	'IS 250 C',
	'IS-F',
	'LS',
	'LX',
	'NX',
	'RC F',
	'RX',
	'RX 300',
	'RX 400h',
	'RX 450h',
	'SC 430',
	'4-Runner',
	'Auris',
	'Avensis',
	'Avensis Combi',
	'Avensis Van Verso',
	'Aygo',
	'Camry',
	'Carina',
	'Celica',
	'Corolla',
	'Corolla Combi',
	'Corolla sedan',
	'Corolla Verso',
	'FJ Cruiser',
	'GT86',
	'Hiace',
	'Hiace Van',
	'Highlander',
	'Hilux',
	'Land Cruiser',
	'MR2',
	'Paseo',
	'Picnic',
	'Prius',
	'RAV4',
	'Sequoia',
	'Starlet',
	'Supra',
	'Tundra',
	'Urban Cruiser',
	'Verso',
	'Yaris',
	'Yaris Verso',
	'i3',
	'i8',
	'M3',
	'M4',
	'M5',
	'M6',
	'Rad 1',
	'Rad 1 Cabrio',
	'Rad 1 Coupé',
	'Rad 2',
	'Rad 2 Active Tourer',
	'Rad 2 Coupé',
	'Rad 2 Gran Tourer',
	'Rad 3',
	'Rad 3 Cabrio',
	'Rad 3 Compact',
	'Rad 3 Coupé',
	'Rad 3 GT',
	'Rad 3 Touring',
	'Rad 4',
	'Rad 4 Cabrio',
	'Rad 4 Gran Coupé',
	'Rad 5',
	'Rad 5 GT',
	'Rad 5 Touring',
	'Rad 6',
	'Rad 6 Cabrio',
	'Rad 6 Coupé',
	'Rad 6 Gran Coupé',
	'Rad 7',
	'Rad 8 Coupé',
	'X1',
	'X3',
	'X4',
	'X5',
	'X6',
	'Z3',
	'Z3 Coupé',
	'Z3 Roadster',
	'Z4',
	'Z4 Roadster',
	'Amarok',
	'Beetle',
	'Bora',
	'Bora Variant',
	'Caddy',
	'Caddy Van',
	'Life',
	'California',
	'Caravelle',
	'CC',
	'Crafter',
	'Crafter Van',
	'Crafter Kombi',
	'CrossTouran',
	'Eos',
	'Fox',
	'Golf',
	'Golf Cabrio',
	'Golf Plus',
	'Golf Sportvan',
	'Golf Variant',
	'Jetta',
	'LT',
	'Lupo',
	'Multivan',
	'New Beetle',
	'New Beetle Cabrio',
	'Passat',
	'Passat Alltrack',
	'Passat CC',
	'Passat Variant',
	'Passat Variant Van',
	'Phaeton',
	'Polo',
	'Polo Van',
	'Polo Variant',
	'Scirocco',
	'Sharan',
	'T4',
	'T4 Caravelle',
	'T4 Multivan',
	'T5',
	'T5 Caravelle',
	'T5 Multivan',
	'T5 Transporter Shuttle',
	'Tiguan',
	'Touareg',
	'Touran',
	'Alto',
	'Baleno',
	'Baleno kombi',
	'Grand Vitara',
	'Grand Vitara XL-7',
	'Ignis',
	'Jimny',
	'Kizashi',
	'Liana',
	'Samurai',
	'Splash',
	'Swift',
	'SX4',
	'SX4 Sedan',
	'Vitara',
	'Wagon R+',
	'100 D',
	'115',
	'124',
	'126',
	'190',
	'190 D',
	'190 E',
	'200 - 300',
	'200 D',
	'200 E',
	'210 Van',
	'210 kombi',
	'310 Van',
	'310 kombi',
	'230 - 300 CE Coupé',
	'260 - 560 SE',
	'260 - 560 SEL',
	'500 - 600 SEC Coupé',
	'Trieda A',
	'A',
	'A L',
	'AMG GT',
	'Trieda B',
	'Trieda C',
	'C',
	'C Sportcoupé',
	'C T',
	'Citan',
	'CL',
	'CL',
	'CLA',
	'CLC',
	'CLK Cabrio',
	'CLK Coupé',
	'CLS',
	'Trieda E',
	'E',
	'E Cabrio',
	'E Coupé',
	'E T',
	'Trieda G',
	'G Cabrio',
	'GL',
	'GLA',
	'GLC',
	'GLE',
	'GLK',
	'Trieda M',
	'MB 100',
	'Trieda R',
	'Trieda S',
	'S',
	'S Coupé',
	'SL',
	'SLC',
	'SLK',
	'SLR',
	'Sprinter',
	'9-3',
	'9-3 Cabriolet',
	'9-3 Coupé',
	'9-3 SportCombi',
	'9-5',
	'9-5 SportCombi',
	'900',
	'900 C',
	'900 C Turbo',
	'9000',
	'100',
	'100 Avant',
	'80',
	'80 Avant',
	'80 Cabrio',
	'90',
	'A1',
	'A2',
	'A3',
	'A3 Cabriolet',
	'A3 Limuzina',
	'A3 Sportback',
	'A4',
	'A4 Allroad',
	'A4 Avant',
	'A4 Cabriolet',
	'A5',
	'A5 Cabriolet',
	'A5 Sportback',
	'A6',
	'A6 Allroad',
	'A6 Avant',
	'A7',
	'A8',
	'A8 Long',
	'Q3',
	'Q5',
	'Q7',
	'R8',
	'RS4 Cabriolet',
	'RS4/RS4 Avant',
	'RS5',
	'RS6 Avant',
	'RS7',
	'S3/S3 Sportback',
	'S4 Cabriolet',
	'S4/S4 Avant',
	'S5/S5 Cabriolet',
	'S6/RS6',
	'S7',
	'S8',
	'SQ5',
	'TT Coupé',
	'TT Roadster',
	'TTS',
	'Avella',
	'Besta',
	'Carens',
	'Carnival',
	'Cee`d',
	'Cee`d SW',
	'Cerato',
	'K 2500',
	'Magentis',
	'Opirus',
	'Optima',
	'Picanto',
	'Pregio',
	'Pride',
	'Pro Cee`d',
	'Rio',
	'Rio Combi',
	'Rio sedan',
	'Sephia',
	'Shuma',
	'Sorento',
	'Soul',
	'Sportage',
	'Venga',
	'109',
	'Defender',
	'Discovery',
	'Discovery Sport',
	'Freelander',
	'Range Rover',
	'Range Rover Evoque',
	'Range Rover Sport',
	'Avenger',
	'Caliber',
	'Challenger',
	'Charger',
	'Grand Caravan',
	'Journey',
	'Magnum',
	'Nitro',
	'RAM',
	'Stealth',
	'Viper',
	'300 C',
	'300 C Touring',
	'300 M',
	'Crossfire',
	'Grand Voyager',
	'LHS',
	'Neon',
	'Pacifica',
	'Plymouth',
	'PT Cruiser',
	'Sebring',
	'Sebring Convertible',
	'Stratus',
	'Stratus Cabrio',
	'Town & Country',
	'Voyager',
	'Aerostar',
	'B-Max',
	'C-Max',
	'Cortina',
	'Cougar',
	'Edge',
	'Escort',
	'Escort Cabrio',
	'Escort kombi',
	'Explorer',
	'F-150',
	'F-250',
	'Fiesta',
	'Focus',
	'Focus C-Max',
	'Focus CC',
	'Focus kombi',
	'Fusion',
	'Galaxy',
	'Grand C-Max',
	'Ka',
	'Kuga',
	'Maverick',
	'Mondeo',
	'Mondeo Combi',
	'Mustang',
	'Orion',
	'Puma',
	'Ranger',
	'S-Max',
	'Sierra',
	'Street Ka',
	'Tourneo Connect',
	'Tourneo Custom',
	'Transit',
	'Transit',
	'Transit Bus',
	'Transit Connect LWB',
	'Transit Courier',
	'Transit Custom',
	'Transit kombi',
	'Transit Tourneo',
	'Transit Valnik',
	'Transit Van',
	'Transit Van 350',
	'Windstar',
	'H2',
	'H3',
	'Accent',
	'Atos',
	'Atos Prime',
	'Coupé',
	'Elantra',
	'Galloper',
	'Genesis',
	'Getz',
	'Grandeur',
	'H 350',
	'H1',
	'H1 Bus',
	'H1 Van',
	'H200',
	'i10',
	'i20',
	'i30',
	'i30 CW',
	'i40',
	'i40 CW',
	'ix20',
	'ix35',
	'ix55',
	'Lantra',
	'Matrix',
	'Santa Fe',
	'Sonata',
	'Terracan',
	'Trajet',
	'Tucson',
	'Veloster',
	'EX',
	'FX',
	'G',
	'G Coupé',
	'M',
	'Q',
	'QX',
	'Daimler',
	'F-Pace',
	'F-Type',
	'S-Type',
	'Sovereign',
	'X-Type',
	'X-type Estate',
	'XE',
	'XF',
	'XJ',
	'XJ12',
	'XJ6',
	'XJ8',
	'XJ8',
	'XJR',
	'XK',
	'XK8 Convertible',
	'XKR',
	'XKR Convertible',
	'Cherokee',
	'Commander',
	'Compass',
	'Grand Cherokee',
	'Patriot',
	'Renegade',
	'Wrangler',
	'100 NX',
	'200 SX',
	'350 Z',
	'350 Z Roadster',
	'370 Z',
	'Almera',
	'Almera Tino',
	'Cabstar E - T',
	'Cabstar TL2 Valnik',
	'e-NV200',
	'GT-R',
	'Insterstar',
	'Juke',
	'King Cab',
	'Leaf',
	'Maxima',
	'Maxima QX',
	'Micra',
	'Murano',
	'Navara',
	'Note',
	'NP300 Pickup',
	'NV200',
	'NV400',
	'Pathfinder',
	'Patrol',
	'Patrol GR',
	'Pickup',
	'Pixo',
	'Primastar',
	'Primastar Combi',
	'Primera',
	'Primera Combi',
	'Pulsar',
	'Qashqai',
	'Serena',
	'Sunny',
	'Terrano',
	'Tiida',
	'Trade',
	'Vanette Cargo',
	'X-Trail',
	'240',
	'340',
	'360',
	'460',
	'850',
	'850 kombi',
	'C30',
	'C70',
	'C70 Cabrio',
	'C70 Coupé',
	'S40',
	'S60',
	'S70',
	'S80',
	'S90',
	'V40',
	'V50',
	'V60',
	'V70',
	'V90',
	'XC60',
	'XC70',
	'XC90',
	'Espero',
	'Kalos',
	'Lacetti',
	'Lanos',
	'Leganza',
	'Lublin',
	'Matiz',
	'Nexia',
	'Nubira',
	'Nubira kombi',
	'Racer',
	'Tacuma',
	'Tico',
	'1100',
	'126',
	'500',
	'500L',
	'500X',
	'850',
	'Barchetta',
	'Brava',
	'Cinquecento',
	'Coupé',
	'Croma',
	'Doblo',
	'Doblo Cargo',
	'Doblo Cargo Combi',
	'Ducato',
	'Ducato Van',
	'Ducato Kombi',
	'Ducato Podvozok',
	'Florino',
	'Florino Combi',
	'Freemont',
	'Grande Punto',
	'Idea',
	'Linea',
	'Marea',
	'Marea Weekend',
	'Multipla',
	'Palio Weekend',
	'Panda',
	'Panda Van',
	'Punto',
	'Punto Cabriolet',
	'Punto Evo',
	'Punto Van',
	'Qubo',
	'Scudo',
	'Scudo Van',
	'Scudo Kombi',
	'Sedici',
	'Seicento',
	'Stilo',
	'Stilo Multiwagon',
	'Strada',
	'Talento',
	'Tipo',
	'Ulysse',
	'Uno',
	'X1/9',
	'Cooper',
	'Cooper Cabrio',
	'Cooper Clubman',
	'Cooper D',
	'Cooper D Clubman',
	'Cooper S',
	'Cooper S Cabrio',
	'Cooper S Clubman',
	'Countryman',
	'Mini One',
	'One D',
	'200',
	'214',
	'218',
	'25',
	'400',
	'414',
	'416',
	'620',
	'75',
	'Cabrio',
	'City-Coupé',
	'Compact Pulse',
	'Forfour',
	'Fortwo cabrio',
	'Fortwo coupé',
	'Roadster'
];

export const apns = [
	{ address: 'soracom.io', user: 'sora', password: 'sora' },
	{ address: 'soracom.io-docomo', user: 'sora', password: 'sora' },
	{ address: 'lte-d.ocn.ne.jp', user: 'mobileid@ocn', password: 'mobile' },
	{ address: '3g-d-2.ocn.ne.jp', user: 'mobileid@ocn', password: 'mobile' },
	{ address: 'iijmio.jp', user: 'mio@iij', password: 'iij' },
	{ address: 'iijmio.jp-ipv4v6', user: 'mio@iij', password: 'iij' },
	{ address: 'iijmio.jp-ipv6', user: 'mio@iij', password: 'iij' },
	{ address: 'iijmobile.jp', user: 'mobile@iij', password: 'iij' },
	{ address: 'iijmobile.jp-ipv4v6', user: 'mobile@iij', password: 'iij' },
	{ address: 'iijmobile.jp-ipv6', user: 'mobile@iij', password: 'iij' },
	{ address: 'iijmobile.biz', user: 'biz@iij', password: 'iij' },
	{ address: 'iijmobile.biz-ipv4v6', user: 'biz@iij', password: 'iij' },
	{ address: 'iijmobile.biz-ipv6', user: 'biz@iij', password: 'iij' },
	{ address: 'internet4gd.gdsp', user: 'web', password: 'web' },
	{ address: 'sd.iijmobile.jp', user: 'mobile@iij', password: 'iij' },
	{ address: 'm2m4biz.softbank', user: 'm2mbiz', password: 'm2mbiz' },
	{ address: 'isp.docomoiot.net', user: 'web', password: 'web' },
	{ address: 'ipsim.net', user: 'sim@with', password: 'sim' },
	{ address: 'rokemoba', user: 'roke@moba', password: 'roke@moba' },
	{ address: 'au.au-net.ne.jp', user: 'user@au.au-net.ne.jp', password: 'au' },
	{ address: 'uqmobile.jp', user: 'uq@uqmobile.jp', password: 'uq' }
];
