#
# Docker compose file for running the monolith dependencies
# databases, rabbitmq, jaeger, etc and the monolith itself
# in docker containers.
#
# this is mostly usefull for testing the monolith container
#

volumes:
  postgres:

networks:
  raster-network:
    name: raster-network
    driver: bridge

services:
  postgres:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: raster-db
    environment:
      POSTGRES_DB: raster_dev
      POSTGRES_USER: raster_user
      POSTGRES_PASSWORD: raster_pass
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - raster-network

  rabbitmq:
    container_name: raster-rmq
    image: rabbitmq:3.10.1-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - raster-network

  jaeger:
    container_name: raster-jaeger
    image: 'jaegertracing/jaeger:2.2.0'
    ports:
      - '4317:4317'
      - '4318:4318'
      - '14250:14250'
      - '14268:14268'
      - '16686:16686'
    networks:
      - raster-network

  rastercar-monolith:
    image: rastercar/monolith
    container_name: raster-monolith
    environment:
      - JAEGER_URL=http://jaeger:4317
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - DATABASE_URL=postgres://raster_user:raster_pass@postgres:5432/raster_dev
    command: ['node', '--env-file', './env/.env.development', 'app']
    ports:
      - '3000:3000'
    depends_on:
      - jaeger
      - postgres
      - rabbitmq
    networks:
      - raster-network

  rastercar-mailer:
    image: rastercar/mailer
    container_name: raster-mailer
    environment:
      - APP_DEBUG=true
      - TRACER_SERVICE_NAME=mailer
      - RMQ_URI=amqp://localhost:5672
      - RMQ_QUEUE=mailer
      - RMQ_CONSUMER_TAG=mailer_service_consumer
      - RMQ_EMAIL_EVENTS_EXCHANGE=email_events
      - AWS_REGION=us-east-1
      - AWS_SES_TRACKING_CONFIG_SET=email-events
      - AWS_SNS_TRACKING_SUBSCRIPTION_ARN=arn:aws:sns:us-east-1:152409327412:email-events:b725dae9-2782-4387-a418-8d279032a767
      - AWS_SES_MAX_EMAILS_PER_SECOND=1
      - HTTP_PORT=3005
      - APP_DEFAULT_EMAIL_SENDER=no-reply@rastercar.com
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
    ports:
      - '3005:3005'
    depends_on:
      - jaeger
      - rabbitmq
    networks:
      - raster-network
