name: Deploy to Homolog

on:
  push:
    branches:
      - homolog

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Check TS types
        run: pnpm check

      - name: Run unit tests
        run: pnpm test:unit

      - name: Run browser unit tests
        run: pnpm test:unit-browser

      - name: Run integration tests
        run: pnpm test:integration

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --build-arg VITE_COMMIT_HASH=$(git rev-parse HEAD) -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      # download task definition to a json file
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --region ${{ secrets.AWS_REGION }} --task-definition monolith-homolog --query taskDefinition > task-definition.json

      # update the file of the task definition to have the new recently built image
      - name: Fill in new image ID in task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: rastercar-monolith
          image: ${{ steps.build-image.outputs.image }}

      # deploy the new task definition to homolog [PROD-TODO]
      # - name: Deploy Amazon ECS task definition
      #   uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      #   with:
      #     task-definition: ${{ steps.task-def.outputs.task-definition }}
      #     service: ${{ secrets.ECS_MONOLITH_HOMOLOG_SERVICE }}
      #     cluster: ${{ secrets.ECS_HOMOLOG_CLUSTER }}

      # - name: Verify ECS deployment
      #   run: |
      #     echo "Deployment to ECS completed successfully!"
